name: Deploy to dist branch

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Switch to dist branch
              run: |
                  git fetch
                  git switch dist || git checkout -b dist

            - name: Move content from src to root
              run: |
                  mv ./src/* ./
                  rm -rf ./src

            - name: Commit and push changes
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add .
                  git commit -m "Move content from src to root"
                  git push origin dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
